from time import sleep

from userbot import CMD_HANDLER as cmd
from userbot import CMD_HELP, owner
from userbot.utils import edit_or_reply, man_cmd


@man_cmd(pattern="p(?: |$)(.*)")
async def _(event):
    await edit_or_reply(event, "**Assalamualaikum Anak Ngentot**")


@man_cmd(pattern="pe(?: |$)(.*)")
async def _(event):
    await edit_or_reply(event, "**Assalamualaikum, Jadi Ngentot Ga?**")


@man_cmd(pattern="P(?: |$)(.*)")
async def _(event):
    xx = await edit_or_reply(event, f"**Haii Salken Saya {owner}**")
    sleep(2)
    await xx.edit("**Assalamualaikum...**")


@man_cmd(pattern="l(?: |$)(.*)")
async def _(event):
    await edit_or_reply(event, "**Wa'alaikumsalam Anak Anjing**")


@man_cmd(pattern="a(?: |$)(.*)")
async def _(event):
    xx = await edit_or_reply(event, f"**Haii Salken Saya {owner}**")
    sleep(2)
    await xx.edit("**Assalamualaikum**")


@man_cmd(pattern="j(?: |$)(.*)")
async def _(event):
    xx = await edit_or_reply(event, "**JAKA SEMBUNG BELI DUREN**")
    sleep(3)
    await xx.edit("**MENDING LU SUREN🔥**")


@man_cmd(pattern="k(?: |$)(.*)")
async def _(event):
    xx = await edit_or_reply(event, f"**HALLO YATIM PIATU {owner}**")
    sleep(2)
    await xx.edit("**LU SEMUA GOBLOK ANJING 🔥**")


@man_cmd(pattern="kntl(?: |$)(.*)")
async def _(event):
    xx = await edit_or_reply(event, "**LU SEMUA KONTOL**")
    sleep(2)
    await xx.edit("**KALO JELEK MINIMAL MANDI NGENTOT**")
    (sleep)(2) 
    await xx.edit("**UDAH JELEK GAPERNAH MANDI**") 
    (sleep)(2) 
    await xx.edit("**KALO GAPUNYA AIR BILANG NGENTOT**") 
    (sleep)(2) 
    await xx.edit("**BIAR GUA KASI AIR COMBERAN ANJING**") 
    (sleep)(2) 
    await xx.edit("**MUKA ITEM KEK KETAN ITEM BANGSAT**") 
    (sleep)(2) 
    await xx.edit("**KAKI LU BANYAK KORENGNYA TOLOL**") 
    (sleep)(2) 
    await xx.edit("**MUKA LU AJA ITU MIRIP MONYET RAGUNAN BEGO**") 
    (sleep)(2) 
    await xx.edit("**DASAR ANAK LUTUNG**") 
    (sleep)(2)
    await xx.edit("**MENDING LU MULUNG**") 
    (sleep)(2)
    await xx.edit("**BOCAH GATAU DI UNTUNG**") 
    (sleep)(2) 
    await xx.edit("**MUKA KAYA GEMBELAN LAMPUNG**") 
    (sleep)(2) 
    await xx.edit("**BUNTUNGG BUNTUNGG**") 


@man_cmd(pattern="roas(?: |$)(.*")
async def _(event):
xx = await edit_or_reply(event, "**YAELAH YAELAH YAELAH MULU LO GOBLOK, NGELUH LO LAWAN GUA? KALO EMANG LO GA MAMPU BUAT LAWAN GUA MAH SURREND AJA TOLOL BOCAH LEMES IDIOT MODAL TYPING NGELANTUR DOANG, LO LIAT NOH TOLOL NAJIS APAANSI GOBLOK LO TYPING AJA GAJELAS BANGET TOLOL NGELANTUR SEMUA NAJIS GUA BAHAS APAAN LO MALAH JAWAB APAAN, GINI NIH KELAKUAN BOCAH YG GAPERNAH MASUK SEKOLAH, KALO SEKOLAH CUMA SAMPE GERBANG DOANG TERUS CABUT CABUTAN MULU KABUR GA BERANI SEKOLAH KARENA TAKUT DIPUKULIN SEMUA ORANG HAHA, GA ADA KAN BEGO YG MAU TEMENAN SAMA LU? KARNA LU NYUSAHIN GOBLOK, TEMENAN SAMA LO GA ADA UNTUNGNYA, YG ADA MALAH JADI BEBAN DOANG, UDAH GITU SUKA MALING LAGI NAJIS JAJANAN WARUNG DIBAWA KABUR MULU KAN SAMA LO, SEGITUNYA AMAT SI LO PENGEN JAJAN SAKING GAPUNYA DUITNYA, MAKANYA JADI ORANG TUH JANGAN MISKIN GOBLOK JADINYA GA ADA KAN YG MAU NAMPUNG LU KARNA LU CUMA JADI BEBAN DOANG TOLOL, LO ITU BEBAN BEGO DIMANA MANA JUGA, BEBAN TONGKRONGAN, BEBAN KELUARGA, BEBAN MASYARAKAT, BEBAN AGAMA, BEBAN NEGARA, POKONYA BEBAN DARI SEGALA BEBAN SEMUANYA ADA DAH TUH DI DIRI LU, JADI MANUSIA GA ADA BAGUS BAGUSNYA SAMA SEKALI ANJING, UDAH MAH MUKA LU JELEK ITEM DEKIL, RAMBUT BERANTAKANA, BIBIR PECAH PECAH MUKA GRADAKAN, GA ADA BAGUS BAGUSNYA SAMA SEKALI LU TOLOL JADI MANUSIA, MENDING JADI ALIEN AJA SONO LO GAJELAS HIDUP LU DONGO, MAKANYA KALO PUNYA OTAK TUH DIPAKE TOLOL BUAT MIKIR, JANGAN BUAT NONTON BOKEP DOANG, SETIAP JAM KERJAANYA COLI MULU TOLOL LO CEKEK MULU ITU PELER LO MAKANYA JADI GOBLOK NAJIS PEMIKIRANNYA GA JALAN UDAH KETUTUP SEMUA SAMA GAMBAR BOKEP, SAKING GA ADA SAMA SEKALI YA CEWE YG MAU SAMA LO MAKANYA LO NGELAMPIASIN NAFSU LO BUAT NGEBOKEP, MAKANYA JADI ORANG TUH YG KEREN NAPA NIH KAYA GUA YG GANTENG GITU YA, MINIMAL MAH BERSIH LAH GOBLOK JADI ORANG TUH MANDI JANGAN DEKIL KAYA LU TUH, GUA TAU PASTI BADAN LU ITU BAU BANGET KAN, BAU SAMPAH BANTAR GEBANG TUH YG SEKARANG UDAH JADI GUNUNG SAMPAH, GITU KAN BAU BADAN LU? HAHA, MANDI GOBLOK ORANG MAH YG BERSIH TERUS PAKE MINYAK WANGI GOBLOK BIAR BADAN LO TUH WANGI GA BAU KAMBING KAYA SEKARANG, APA JANGAN JANGAN LO GA MAMPU JUGA BUAT BELI MINYAK WANGI? OIYA GUA LUPA LO KAN BOCAH MISKIN WKWK, HADEH DASAR BOCAH MISKIN TOLOL, LO CERPENIN BALIK NIH YE TYPINGAN GUA, AWAS KALO LO BALASNYA SINGKAT DONGO, NGEHINA LU JUGA GAUSAH PAKE MIKIR JUGA UDAH GOBLOK WKWK, MUKA BERUK TIAP HARI JUALAN BALON MUKANYA MIRIP BOCAH DEMO DIPAKEIN ODOL SAMA LILIN BIAR DIKATA GLOW UP PADAHAL YAELAH GADA SAMA SEKALI YANG ADA NI YE CEWE AJA OGAH DEKETIN LO GOBLOK KAGA KUAT DIA PENGEN KETAWA SAMPE MENCRET LIAT MUKA LO TOLOL HAHA NAJIS UDAH KELURGA NYA SETENGAH SETENGAH DOANG KAYA APPLE IPHONE, UDAH MAH YA LO IRI KAN PASTI LIAT KELUARGA GUA YANG UTUH INI YAHAHA**")


@man_cmd(pattern="roass(?: |$)(.*")
async def _(event):
xx = await edit_or_reply(event, "**MAKANYA PUNYA KELUARGA ITU JANGAN KELUARGA HARAM,UDAH ANAKNYA HARAM LAHIR DARI KONDOM BOCOR BEGO,LU ITU SEBENERNYA ANAK YG TIDAK DIINGINKAN AMA NYOKAP BOKAP LU TOLOL,TUHAN ITU NYIPTAIN ELU CUMA PAS GABUT DOANG,LU ITU GADA GUNA NYA DI DUNIA INI BEGO EGEGEGEG,NIH YA ASAL LU TAU MAK LU ITU KERJANYA CUMA JADI LONTE YANG MANGKAL DI PINGGIR2 JALAN TUH,YG SEKALI MAEN CUMA DI BAYAR ROKO FILTER DUA BATANG SAMA GRANITA SATU,MAK LU ITU UDAH MURAH BET MURAH,SANGKING GADA HARGANYA,BAPAK LU AMPE NGAWININ EMAK LU KARNA BAPAK LU MAUNYA YANG GRATISAN DOANG BEGO EGEGEGEG,GUA TAU ORANG ORANG SUSAH KEK ELU TUH JARANG MAKAN ENAK,MAKAN DAGING CUMA SETAUN SEKALI,ITU JUGA NUNGGU KUPON KURBAN,MAKANAN SEHARI HARI LU KAN CUMA TAHU TEMPE PAKE KUACI EGEGEG,PANTES BET PANTES LU BUSUNG LAPAR,MAKANYA NIH KALO GAPUNYA DUIT NGOMONG GITU KE GUA TOLOL,BIAR GUA KEPRET² DUIT DEPAN MUKA LU EGEGEGEG,KASIAN BET KASIAN GUA AMA LU,UDAH HIDUP SUSAH TAMPANG BURUK RUPA YEKAN MANA MAU GITU CEWE AMA LU,SEKALINYA ADA YANG MAU ITU CEWE CEWE MICHAT BIGOLIVE EGEGEG PEREK MURAHAN,MAK LU AJA KALO LAGI LIVE DI BIGO NIH,GADA YG NONTON BEGO KARNA EMAK LU TUH JELEK BET JELEK BEGO EGEGEG,KALO MAK LU LAGI LIVE ITU YG NONTON CUMA GUA TERUS GUA GIFT KARNA GUA KASIAN YEKAN EGEGEG, BOKAP LU YANG KLO KETEMU GUA SUJUD SUJUD NYEMBAH NYEMBAH GUA TERUS PALA BELAKANG NYA GUA GEDIK,TERUS BAPA LU NGEMIS² AMA GUA MINTA ROKO,KELUARGA SUSAH,RUMAH NYA DARI TRIPLEK YANG SEKALI GUA KENCINGIN LANGSUNG RUBUH,TIDUR DI TANAH MAKANYA BADAN LU TUH BANYAK BOPENG BEGO EGEGEG,GUA NIH KALO SANGE YA,GUA TELPON MAK LU TERUS MAK LU NYEPONG KONTOL GUA NGEWE AMA GUA,KALO LU GAPERCAYA NIH GUA ADA VIDEONYA,KEMAREN MALEM MAK LU NGENTOT AMA GUA,BARANG KALI LU MAU YEKAN VIDEO NYA,BUAT BAHAN COLI LU EGEGEEG, MEMEK MAK LU TUH LEBAR BET LEBAR KEK GENTONG SPANYOL,MEMEK MAK LU TUH SEMUA BARANG BISA MASUK,CANGKUL,SAPU IJUK,POKONYA BARANG BARANG YG GEDE ITU BISA MASUK KE MEMEK MAK LU,TERUS UDAH GITU KONTOL BOKAP LU YANG SIPILIS DI PALKON NYA,TERUS ANAKNYA KONTOL NYA BISA DI COPOT PASANG KEK LEGO,UDAH GITU KENA RAJA SINGA LAGI EGEGEGE,MIRIS BET MIRIS BEGO GUA,LU TUH GA COCOK BEGO WAR AMA GUA,KOSAKATA LU AJA DARI TADI GITU GITU DOANG,KOSA KATA LU AJA MASIH KOSA KATA DASAR,MAKANYA NIH LU KALO MAU WAR AMA GUA,BELI BUKU KOSA KATA DI GRAMEDIA,OHH IYA GUA LUPA DI DAERAH LU MANA ADA GRAMEDIA LU KAN BOCAH KAMPUNG DEKIL LUSUH,HP AJA J2 PRIME RAM 2 GB INTERNAL 16 SEKALI MAEN GAME LANGSUNG MATI LAYAR LCD CUMA SEPARO TERUS HP NYA DI LAKBANIN EGEGEGEG,MAKANYA NIH TOLOL GUA KASIH TAU AMA LU,KALO KELUARGA LU UDAH SUSAH,LU NYA JUGA JANGAN NYUSAHIN,SEKOLAH TU JANGAN SAMPE DEPAN GERBANG DOANG TOLOL,LU NIH SEKALINYA SEKOLAH CUMA NYOLONG GORENGAN DI KANTIN,MANA OTAK GOBLOK YEKAN MASUK NEGRI GABISA MASUK SWASTA GA MAMPU ADUHH KASIAN GUA AMA LU,MAKANYA KLO PUNHA OTAK JANGAN CUMA SETENGAH SENDOK NYAM NYAM,PUNYA OTAK TUH DI PAKE JANGAN CUMA DI PAJANGIN DOANG TOLOL EGEGEG,BAPAK LU ITU UDAH BAU TANAH BEGO,BENTAR LAGI PENGEN MATI TERUS MASUK NERAKA,EH BAPAK LU KLO MASUK NERAKA ITU GA ADA SESI TANYA JAWAB,LANGSUNG AE DI CEMPLUNGIN KE API NERAKA,GUA TAU BEGO LU ITU ANAK CACAT LAHIR DALAM KEADAAN CACAT,MANA KAKI BUNTUNG BIBIR SUMBING GIHI KUNING MATA CUMA SATU DOANG KEK DAJAL,NIH GUA KASIH TAU YA AMA LU,KUBURAN MAK LU ITU GUA GALI GALI TOLOL,TERUS GUA BERAKIN YEKAN BIAR MAK LU DI NERAKA BAU TAI TUH EGEGEGEG,MAK LU AJA MENINGGAL GA DI TERIMA AMA BUMI!!**")


@man_cmd(pattern="ros(?: |$)(.*")
async def _(event):
xx = await edit_or_reply(event, "**ASTAGA ANAK ANJING JANGAN SO SO AN TYPING AMA GUA KONTOL, GABAKAL ADA SUREND SUREND NYA GUA YA YA, YAUDAH SINI ADU CERPEN SAMA GUA YA TUKANG GALON GOBLOK BANGSAT BIADAP, GUA TAU LU CUMA TUKANG GALON NGENTOD, ABIS KERJA LU CARI VCS AN SANA SINI DI TELEGRAM, KARENA APA? KARENA LU TU BOCAH SAGAPUNG YANG BUTUH PERHATIAN NGENTOD, GUA LIATIN DARI DULU LU CUMA JADI BADUT DIMANA MANA KAGA ADA AKSI YA KAN, GIMANA MAU ADA AKSI KAPABALITIS AJA KAGA ADA, ALIAS APA? ALIAS KOSONG GOBLOK, MANUSIA DAN MAKHLUK HINA YANG KAYAK GINI NI YANG HARUS DI HUJANI DENGAN KOSA KATA, DI INJEK PAKE PEDAL GAS MOBIL TRUK, MANUSIA DARI LAHIR UDAH CACAT FISIK CACAT MENTAL, KAGA KEURUS  DARI LAHIR SAMA ORANG TUA, CUMA BISA NGEBACOT SANA SINI TANPA NAIKIN NAMA, YANG ADA MALAH NURUNIN NAMA YANG UDAH DI CAP JELEK DIMANA MANA, GUA JELASIN YA SAMA LU ANAK ANAK DARI SEORANG PELACUR, MATI NYA BAPALO ITU KARENA GUA SAMBIT PAKE PARANG GUA CAMBUK PAKE EKOR SAPI KARENA APA? KARENA MELAKUKAN PERZINAAN SAMA IBU KANDUNG GOBLOK, MAKANYA LU TU SADAR DIRI NGENTOD, MENDING SINI GUA JADI AYAH LU AJA, NTAR GUA KASIH JAJAN ASAL KAN IBU LU GUA EWE SAMA TEMEN TEMEN GUA HAHHAHA, GOBLOK GOBLOK MENDING JADI PENGEMIS AJA DEH LU DIJALAN KARENA GUA UDAH MULAI MIRIS SAMA KEHIDUPAN LU YANG UDAH LUNTANG LANTUNG KESANA KEMARI AKWKWKW, KONTOL KONTOL BAHAHA ORANG PINTER KAYAK GUA GK PANTES BUAT NGELADENIN ORANG YANG SEKOLAH SAMPE DEPAN PINTU GERBANG DOANG KASIAN BAPAK LO NGEBAJAK SAWAH ORANG SAMPE PINGSAN DI SAWAH TERUS DI INJEK INJEK SAMA KEBO PALA NYA SAMPE ANCUR TERUS MAK LO JADI BABU CUCI DAN NGEWE PAKSA SAMA MAJIKANNYA BUAT NYEKOLAIN LO EH MALAH DUIT SPP NYA LO TILEP BUAT NYEWA TANTE TANTE PADAHAL TANPA LO NYEWA DAN LO MINTA SAMA IBU LO PASTI DI KASIH DAN LEBIH KASIAN NYA MEMEK MAK LO UDH PAS BUSRIK DAKIAN NANAHAN DAN LOBANG NYA UDH GEDE BANGET KAYAK TEROWONGAN CASABLANCA LO TAU CASABLANCA GK?GUA YAKIN LO GK TAU LO TUH CUMA ORANG KAMPUNG YANG GK BISA JALAN JALAN KE KOTA BESAR SEPERTI KOTA AKARTA MKANYA TUH HIDUP DI KOTA BIAR GK SERBA SUSAH DAN KEKURANGAN SEPERTI HIDUP LO, WOI KONTOL NYOKAP LO AJA DAH MATI ANJING HADEH GINI NIH BUDAK,KURCACI,DOYOK NAH ITU COCOK SLOGAN BUAT LO KARNA APA? KARNA LO GA PANTES DI PANGGIL NAMA,SOALNYA NAMA" KAYA LO UDAH BANYAK DI BATU NISAN,MENDINGAN LO NYUSUL SONO ORANG TUA LO DI NERAKA,BIAR LO LIAT ORANG TUA LO DI SIKSA ,BAPAK LO KONTOLNYA DI CAMBUKIN YAKAN,EMAK LO MEMEK NYAA DI COLOK" BESI PANAS KARNA APAA? KARNA DI DUNIA BAPAKLO ITU KERJAANNYA NGEGAY,KARNA MATI RASA ,PRUSTASI LIAT EMAK LO YANG KERJAAN NYA JADI PELACUR  TERUS KARNA LIAT BAPAK LO SEORANG PENGANGGURAN,MALES KERJA,KEBNYAKAN NARKOBA YAKAN,MAKANNYA EMAK LO ITU PEKERJAAN JDI PELACUR BUAT APAA? BUAT JDI TULANG PUNGGUNG,TOLOL,MAKANNYA LO JADI ANAK JANGAN BEBANNIN MULU ,UDAH BEBAN ORTU,BEBAN NEGARA,BEBAN TELE,YAKAAN,SEKARANG LO NIHH KAN UDAH TINGGAL SNDIRI DI DEPAN RUKO,NAH GUA PUNYAA SOLUSI BIAR LO BISA MEMBIAYAI HIDUP,APA SOLUSINYAA? NAHH LO KAN MASIH SEKOLAH NII,YAUDH MASUK SEKOLAH JAM 6,LU BERANGKAT SEKOLAH KAN NAIK ANGKOT,TAPI LO KAN GA PUNYA BIAYA YAUDH LU SEPONGIN AJA SUPIR NYA BIAR GRATIS,TERUS PULANG JAM 12,LU GANTI BAJU COREET" DAH BADAN LU JDI SILVER NAH TERUS KE LAMPU MERAH JADI MANUSIA SILVER,PAS PULANGNYA  JAM 3 ,LU NGAMEN DI JALANAN KEK APA KEK GITU,NAH LO PULANGNYA JAM 6 UDAH JAM 6 LU GA PERLU MANDI ,GUA TAU LU ALERGI MANDII,YAUDH MALAMNYAA JADI TUKANG PARKIR INDOMART,SMPE JAM 9 NAH JAM 9 LO NONGKRONG JADI BENCONG AJG**")


@man_cmd(pattern="roas(?: |$)(.*")
async def _(event):
xx = await edit_or_reply(event, "**YAELAH GALANG RAMBU ANARKI MUKA KEK PUKI KEK ANAKAN YOHI KONTOL SOK SOKAN MAU REP PANJANG AMA GUA. GUA TAMPUNG LU KONTOL SEMUA MUMPUNG GIA BAIK HATI DAN TIDAK SOMBONG NIH BABI LONIA DASAR ANJING LAUT MENDING MATI AJA SONO IKUT BAPAKLU KE NERAKA TOLOL MUKA KEK KONTOL MONYET JAUH JAUH DAH SONO LU DASAR MAKHLUK ASTRAL KALO JALAN AJA KESAMPING KEK KEPITING SINI GUA LAWAN LU ANJING MUMPUNG GUA LAGI BORING MENTAL LEMAH TYPINGAN TIPIS KEK SISA HIDUP LU ET GOBLOK LAWAN YANG GA SEBERAPA MANUSIA SETENGAH POPOL AND KUPA MENDING LU LONCAT DARI POHON KELAPA BIAR CEPET NGIRIM LU KESURGA KARNA UDAH KEABISAN KOSAKATA BELOM APA APA NYALI LO UDAH GA ADA KONTOL BOCAH IDIOT KALO SANGE KE SEMAK SEMAK JIJI SANGE GA MODAL CUMA MOKONDO TAU MOKONDO GA LU, MODAL KONTOL DOANG, INGET AJAL LU UDAH DEKET GOBLOG TYPINGAN TIPIS LU GA BIKON GUA GETER TOLOL, MANUSIA MENJIJIKAN BAU TANAH HAHATANAH LIAT NAJI MENJIJIKAN SEKALI MANUSIA KOTNTOL YANG MEMBALUTKAN MENJADI KUBU SLOWLY KONTOL, DAH LAH MENDING SURREND AJA TOLOL BOCAH KAYA LU KLO KE KAFE BAWA TEH GELAS TUNJUKIN KALO LU BERKUALITAS BACOTAN MUTER MULU KAYA KIPAS TAUNYA HANYA SEBATAS KUTU KUTU YANG BERBARIS DASAR BOCAH AUTIS BACOTAN TERLALU TIPIS KEK SISA HIDUP LU TIPIS NAJISIN BGT DAH, ET DONGO MENDING LU SURREND KONTOL SAMPAH ANJING GOBLOK, TIDUR KONTOL, BESOK LU MULUMNG, MULUNG DI KOMPLEK GUA, TUHAN AJA GAMAU NGANGGEP LU UMATNYA APALAGI EMAK BAPAKLO KONTOL BIADAB, NIH UDH MALEM GUA TAU LU LAPER ABIS ITU NUNGGU TIKUS MATI DIPINGGIR JALAN, GALANG KONTOL YANG HIDUP NYA DI JEMBATAN KONTOL JANGAN LAGI LAGI LAWAN GUA YA KONTOL DARITADI GUA TUNGGUIN TYPINGAN LAMA LU GOBLOK, ABIS INI LU LONCAT DARI PHON KELAPA YA, SEPERTI YG TADI GUA BILANG, LO ITU CUMA SEBATAS KUMPULAN PARA BABI YANG GA ADA AKSI HAHA DISURU BELI MICIN MALAH BELI FILTER GA ADA OTAK EMANG YE MENJIJIKAN POKONYA KUBU SLOWLY, EH SATU LAGI NIH YANG BIKIN GUA MALES LAWAN LU, KALO TYPING JANGAN KOPAS YA KONTOL, KARNA GUA TAU JARI LO CUMA SATU PASTI COPAS HAHAHA DONGO MONYET, DASAR PELER AYAM MUKA KAYA JEMBUT SAPI, KENA STROKE HIDUPNYA SETIAP HARI CUMA REBAHAN DIKASUR MAKAN BOKER KENCING AMPE BAUNYA NGELEBIHIN BAU BANGKAI SAMPE DIDEMO SATU DESA GEGARA NGERACUNIN TETANGGA LU SADAR DIRI TOLOL UDAH DIUSIR LU KAGA DIANGGEP DI KAMPUNG LU MENDING LU PERGI BALIK LAGI KEHUTAN LU BIKIN RUMAH YANG DARI RANTING ATAP ALANG ALANG ALAS TIDUR DAUN PISANG KAN LU AWAL TADI UDAH DIBILANG TARZAN KEKOTA NYARI MAK BARU JUGA KETEMU LANGSUNG DIUSIR KAN TOLOL YE, MAKANYA ADEK LU URUSIN AJARIN AKHLAK YANG BENER BUKANNYA HARI HARI NYEPONGIN KONTOL OM OM TETANGGA TOLOL CUMA BIAR DAPET DUIT BUAT JAJAN SABAN HARI YE ADIK AMA MAK SIFAT 11 12 NAJIS TOLOL LU DARI BAYI UDAH DIKUCILIN DIHINA HINA DASAR MANUSIA GA BERGUNA**")


CMD_HELP.update(
    {
        "salam": f"**Plugin : **`salam`\
        \n\n  •  **Syntax :** `{cmd}p`\
        \n  •  **Function : **salam \
        \n\n  •  **Syntax :** `{cmd}pe`\
        \n  •  **Function : **salam Kenal dan salam\
        \n\n  •  **Syntax :** `{cmd}l`\
        \n  •  **Function : **Untuk Menjawab salam\
        \n\n  •  **Syntax :** `{cmd}a`\
        \n  •  **Function : **coba aja dongo\
        \n\n  •  **Syntax :** `{cmd}j`\
        \n  •  **Function : **Kasi Pantun.\
        \n\n  •  **Syntax :** `{cmd}kntl`\
        \n  •  **Function : **hina orang jelek\
        \n\n  •  **Syntax :** `{cmd}roas`\
        \n  •  **Function : **roasting kacung!!!.\
        \n\n  •  **Syntax :** `{cmd}roass`\
        \n  •  **Function : **Coba Aja Tolol!!!🔥\
        \n\n  •  **Syntax :** `{cmd}ros`\
        \n  •  **Function : **Coba Aja Tolol!!!🔥\
        \n\n  •  **Syntax :** `{cmd}ross`\
        \n  •  **Function : **Coba Aja Tolol!!!🔥\
    "
    }
)
